### ISSUE TITLE
speed up loading of sparse coord format

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#13]
speed up loading of sparse coord format. use batch constructors instead of setting each value separately

**Comment by rcurtin** [comment]
I can handle this; it'll be rewritten as part of the refactor to coordinate list format (currently ongoing).

**Comment by conradsnicta** [comment]
we can probably also push this for 7.900, prior to the Big Sparse Rewrite Event (tm) in 8.x :-)

**Comment by conradsnicta** [comment]
The work-in-progress CoMat class might be of help here.  It would certainly simplify the code for loading.

**Comment by conradsnicta** [comment]
refactored to use the map based cache
