### ISSUE TITLE
pkgconfig armadillo.pc generated incorrectly

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#16]
@SoapGentoo - With the new CMakeLists.txt, armadillo.pc is no longer generated incorrectly.  I get the following on a Fedora 24 system, where the `libdir` and `includedir` are missing:

> $ cat /usr/lib64/pkgconfig/armadillo.pc
> prefix=/usr
> exec_prefix=${prefix}
> libdir=
> includedir=
> 
> Name: armadillo
> Description: Fast C++ matrix library with syntax similar to MATLAB and Octave
> URL: http://arma.sourceforge.net
> Version: 7.899.0
> Cflags: -I${includedir}
> Libs: -L${libdir} -larmadillo`

**Comment by conradsnicta** [comment]
sorry, my bad -- didn't update the corresponding `armadillo.pc.in` in the manual change

**Comment by h00shi** [comment]
I think that this issue still persists.

I tried installing the latest version (8.400) according to the README.txt on a local folder. The generated armadillo.pc, however, still points to /usr/... directories.

```
pwd
/home/hooshi/arma-test/
```

```
wget http://sourceforge.net/projects/arma/files/armadillo-8.400.0.tar.xz
tar xJf armadillo-8.400.0.tar.xz
mkdir armadillo-8.400.0-install
cd armadillo-8.400.0
cmake .
make install DESTDIR=/home/hooshi/arma-test/armadillo-8.400.0-install/
```

```
cat /home/hooshi/arma-test/armadillo-8.400.0-install/usr/lib/x86_64-linux-gnu/pkgconfig/armadillo.pc

libdir=/usr/lib/x86_64-linux-gnu
includedir=/usr/include

Name: armadillo
Description: Fast C++ matrix library with syntax similar to MATLAB and Octave
URL: http://arma.sourceforge.net
Version: 8.400.0
Cflags: -I${includedir}
Libs: -L${libdir} -larmadillo
```

**Comment by conradsnicta** [comment]
@h00shi - If you know how to fix this, please submit a patch and/or a pull request.  I'm currently busy with a few other things.

**Comment by h00shi** [comment]
If you are willing to use ```-DCMAKE_PREFIX_PATH=/install/path``` rather than the current ```make install DESTDIR=/install/path```, it should be straightforward. Otherwise, I need to think about it, since you are generating the .pc file before the running make install.

**Comment by conradsnicta** [comment]
@h00shi 
> Is there any reason that using ```DESTDIR``` is mentioned in the readme rather than ```CMAKE_INSTALL_PREFIX```?

It's been a while since I looked at that section, so it's probably a bug in the readme. The cmake installation script has evolved over time, while the corresponding parts in the readme file weren't updated. Could you submit a pull request to correct it?
