### ISSUE TITLE
CMake requirement too high for RHEL & CentOS 7.2 or earlier

### ISSUE THREAD

**Issue by bee-rock** [conradsnicta/armadillo-code#17]
The CMake version required to build Armadillo is currently set to 2.8.12. CMake 2.8.12 wasn't supplied with CentOS 7 until 7.3.1611 which was only released in December 2016: 
https://lists.centos.org/pipermail/centos-announce/2016-December/022172.html

Note that CMake 2.8.11 is supported on CentOS7 until 2024:
https://cmake.org/Wiki/CMake_Life_Cycle_Considerations#cite_note-4

Other libraries have also been maintaining support for CMake 2.8.11 for example:
https://github.com/Unidata/netcdf-c/blob/master/CMakeLists.txt (https://github.com/Unidata/netcdf-c/issues/135)
https://github.com/Valloric/ycmd/pull/162/files

Please consider reducing the CMake 2.8.12 requirement.

**Comment by conradsnicta** [comment]
As far as I know, CentOS 7.x maintains backwards compatibility with earlier minor releases (ie. x-1), so upgrading to the latest series in 7.x should be relatively painless.  Furthermore, CentOS 7.2 is no longer officially supported, so from a security perspective it's a bad idea to keep using 7.2:
http://mirror.aarnet.edu.au/pub/centos/7.2.1511/readme

CentOS 7.3 does indeed have an official package for CMake 2.8.12, so it's not clear why the previous 2.8.11 version would be used.  It's possible to install 2.8.11 directly from the cmake site, but that's in effect an unsupported configuration in CentOS.
http://mirror.aarnet.edu.au/pub/centos/7.3.1611/os/x86_64/Packages/

Incidentally, CentOS 6.8 has CMake 2.8.12, which seems to be dated 17-Oct-2014:
http://mirror.aarnet.edu.au/pub/centos/6.8/os/x86_64/Packages/

I'm not keen on going backwards with the minimum requirement for CMake, as I only test on recent releases of Fedora, Ubuntu LTS and CentOS.

**Comment by bee-rock** [comment]
@conradsnicta Thanks for the reply. Redhat backports it's security fixes. Does CentOS not? Or do I have a misunderstanding about that? https://access.redhat.com/security/updates/backporting/ 

CMake 2.8.11 is used, and has such a long support life, because that's what CentOS/RHEL 7.0 was shipped with:
http://vault.centos.org/centos/7.0.1406/os/x86_64/Packages/ (cmake-2.8.11-4.el7.x86_64.rpm)

I do, however, sympathize in your dismay.

**Comment by conradsnicta** [comment]
@bee-rock - I don't think the support for CentOS is the same as Red Hat.  The former is free, the latter is paid, where you have more options. I believe CentOS simply keeps up with the latest release of RHEL, and abandons anything not current. In other words, CentOS 7.2 is ancient history and not supported.

Anyway, you can modify the minimum requirement for CMake to tailor it to your needs, but as the saying goes: if it breaks, you get to keep all the pieces.

**Comment by bee-rock** [comment]
Where did you find that argument? I never said "can't", I said it wasn't easy.

That was the first thing I tried before opening this issue (enforce only 2.8.11) but it didn't work out of the box. Anyway, thanks for quick responses and the suggestion, cheers.
