### ISSUE TITLE
clamp doesn't work on cubes

### ISSUE THREAD

**Issue by bno1** [conradsnicta/armadillo-code#18]
The clamp function doesn't work on Cubes. The documentation doesn't state if this is intended or not.

**Comment by eddelbuettel** [comment]
Do you want to patch it so it does?

**Comment by conradsnicta** [comment]
yeah, it's currently not implemented for cubes. if you write the code for it, please create a pull request.

**Comment by conradsnicta** [comment]
implemented.

**Comment by conradsnicta** [comment]
@bno1 - expanded clamp() is part of the new release:
http://sourceforge.net/projects/arma/files/armadillo-7.900.1.tar.xz

**Comment by bno1** [comment]
awesome, thank you!
