### ISSUE TITLE
strangely unused variable in SymEigsSolver class

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#2]
@yixuan - while looking through the C++ ARPACK code in Armadillo, I've found two possible issues.

In the function eigenvalues() in the SymEigsSolver class, there is a variable called "j" that seems to be used with no real purpose.  See line 404:
https://github.com/conradsnicta/armadillo-code/blob/master/include/armadillo_bits/newarp_SymEigsSolver_meat.hpp#L404

There is an increment on line 410, but afterwards "j" is no longer used.

Is "j" meant to be used somewhere later, or is there some missing logic here? For example, in the eigenvectors() function that's defined after eigenvalues(), "j" is being used.

**Comment by conradsnicta** [comment]
@yixuan - update.  The eigenvalues() function in the GenEigsSolver class does indeed use "j", to construct the "res" vector.  However, the eigenvalues() function in the SymEigsSolver class does not.  I presume "j" is meant to be used to construct the "res" vector ?

**Comment by yixuan** [comment]
It is indeed a bug. Line 409 should be `res(j) = ritz_val(i)`. Thanks for catching this.

(The current code passes the test because for most cases `i` and `j` will be the same, but when some of the eigenvalues do not converge, they will be different and lead to logical errors.)

**Comment by conradsnicta** [comment]
Fixed. I've also made minor changes which make it easier for compilers to apply RVO (return value optimisation).

**Comment by conradsnicta** [comment]
test 123
