### ISSUE TITLE
const restored due to regressions

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#20]
@adah1972 - I had to restore all of the const declarations in the unstable branch due to regressions that turned up in testing.

The main problem stems from the use of fixed size matrices.  For example, the following code would no longer compile under gcc 6.3:

     arma::mat33 X;
     X.fill(123);
     
     double y = 456;
     X = X/y;

gcc 6.3 produced this:
fixedbug.cpp:17:17: error: ambiguous overload for ‘operator=’ (operand types are ‘arma::mat33 {aka arma::Mat<double>::fixed<3ull, 3ull>}’ and ‘arma::enable_if2<true, const arma::eOp<arma::Mat<double>::fixed<3ull, 3ull>, arma::eop_scalar_div_post> >::result {aka const arma::eOp<arma::Mat<double>::fixed<3ull, 3ull>, arma::eop_scalar_div_post>}’)
   X = X/y;

... followed by a bunch of mostly irrelevant candidate functions.

clang 3.8 had no problem compiling the code, so I'm not exactly sure what's going on.  Either it's a bug in gcc or there is some subtlety in the C++ standard that I haven't picked up on. Either way. I don't have the time to analyse this problem deeply, so I've restored all of the const declarations to avoid regressions.

**Comment by adah1972** [comment]
Hi Conrad,

After a careful check, it turned out that the regression was not caused by the lack of `const`, nor was it eliminated by the addition of `const`. It was caused by my accidentally changing `Mat&` to `fixed&` when I modified the code and not noticing this strange side-effect of GCC.

In order to solve the problem, this was the necessary patch from your change (based on commit 4500d0d):

```diff
diff --git a/include/armadillo_bits/Mat_bones.hpp b/include/armadillo_bits/Mat_bones.hpp
index e583c58..7fd9956 100644
--- a/include/armadillo_bits/Mat_bones.hpp
+++ b/include/armadillo_bits/Mat_bones.hpp
@@ -767,18 +767,18 @@ class Mat<eT>::fixed : public Mat<eT>
   using Mat<eT>::operator();
   
   #if defined(ARMA_USE_CXX11)
-    inline            fixed(const std::initializer_list<eT>& list);
-    inline fixed& operator=(const std::initializer_list<eT>& list);
+    inline          fixed(const std::initializer_list<eT>& list);
+    inline Mat& operator=(const std::initializer_list<eT>& list);
     
-    inline            fixed(const std::initializer_list< std::initializer_list<eT> >& list);
-    inline fixed& operator=(const std::initializer_list< std::initializer_list<eT> >& list);
+    inline          fixed(const std::initializer_list< std::initializer_list<eT> >& list);
+    inline Mat& operator=(const std::initializer_list< std::initializer_list<eT> >& list);
   #endif
   
-  arma_inline fixed& operator=(const fixed<fixed_n_rows, fixed_n_cols>& X);
+  arma_inline Mat& operator=(const fixed<fixed_n_rows, fixed_n_cols>& X);
   
   #if defined(ARMA_GOOD_COMPILER)
-    template<typename T1,              typename   eop_type> inline fixed& operator=(const   eOp<T1,       eop_type>& X);
-    template<typename T1, typename T2, typename eglue_type> inline fixed& operator=(const eGlue<T1, T2, eglue_type>& X);
+    template<typename T1,              typename   eop_type> inline Mat& operator=(const   eOp<T1,       eop_type>& X);
+    template<typename T1, typename T2, typename eglue_type> inline Mat& operator=(const eGlue<T1, T2, eglue_type>& X);
   #endif
   
   arma_inline const Op< Mat_fixed_type, op_htrans >  t() const;
diff --git a/include/armadillo_bits/Mat_meat.hpp b/include/armadillo_bits/Mat_meat.hpp
index 3f0f43d..1e81c5d 100644
--- a/include/armadillo_bits/Mat_meat.hpp
+++ b/include/armadillo_bits/Mat_meat.hpp
@@ -8200,7 +8200,7 @@ Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::fixed(const std::string& text)
   template<typename eT>
   template<uword fixed_n_rows, uword fixed_n_cols>
   inline
-  Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>&
+  Mat<eT>&
   Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::operator=(const std::initializer_list<eT>& list)
     {
     arma_extra_debug_sigprint();
@@ -8236,7 +8236,7 @@ Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::fixed(const std::string& text)
   template<typename eT>
   template<uword fixed_n_rows, uword fixed_n_cols>
   inline
-  Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>&
+  Mat<eT>&
   Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::operator=(const std::initializer_list< std::initializer_list<eT> >& list)
     {
     arma_extra_debug_sigprint();
@@ -8253,7 +8253,7 @@ Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::fixed(const std::string& text)
 template<typename eT>
 template<uword fixed_n_rows, uword fixed_n_cols>
 arma_inline
-Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>&
+Mat<eT>&
 Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::operator=(const fixed<fixed_n_rows, fixed_n_cols>& X)
   {
   arma_extra_debug_sigprint();
@@ -8277,7 +8277,7 @@ Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::operator=(const fixed<fixed_n_rows,
   template<uword fixed_n_rows, uword fixed_n_cols>
   template<typename T1, typename eop_type>
   inline
-  Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>&
+  Mat<eT>&
   Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::operator=(const eOp<T1, eop_type>& X)
     {
     arma_extra_debug_sigprint();
@@ -8310,7 +8310,7 @@ Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::operator=(const fixed<fixed_n_rows,
   template<uword fixed_n_rows, uword fixed_n_cols>
   template<typename T1, typename T2, typename eglue_type>
   inline
-  Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>&
+  Mat<eT>&
   Mat<eT>::fixed<fixed_n_rows, fixed_n_cols>::operator=(const eGlue<T1, T2, eglue_type>& X)
     {
     arma_extra_debug_sigprint();
```

Would you please reconsider the reversion?

**Comment by conradsnicta** [comment]
I'm ok with having the const declarations removed again for the sake of progress, though I'm also not keen on having potential undiscovered regressions.  Gcc and clang disagreed on whether removing the const declarations was a problem. I also haven't tested the changes yet on the crapola MSVC "compiler", which is known to have random hissy fits.

I would prefer to understand the root cause of the problem.  At first sight it doesn't make sense for the overloads to be ambiguous just because the return type has changed.  Without understanding the root cause it's entirely possible that we're doing something wrong, which can come back and bite us later. The errors also suggest that there is a bug in either gcc (rejects valid code) or clang (accepts invalid code).

As Armadillo is used as a platform by many projects, I prefer not to release new versions without thorough testing and debugging.  As such, I'll release version 7.900 with the const declarations as in version 7.800, to avoid potential breakage.

The const declarations can be removed again in the "unstable" version on GitHub, after 7.900 is released.

**Comment by adah1972** [comment]
Hi Conrad,

GCC and clang did not disagree on whether removing the const declarations was a problem. It was only the return type of `operator=`, which I accidentally changed. That was the part where GCC and Clang disagreed (not the const part).

I feel it should be safe and correct to remove the const, as does the usual C++ classes.

**Comment by adah1972** [comment]
By the return type of `operator=`, I meant `Mat&` vs. `fixed&`. GCC and Clang disagreed, no matter whether the `const` is there or not.

**Comment by conradsnicta** [comment]
ok, I see your point.  Could you send in a new pull request?  Please make sure the return types are correct for all of the nested `fixed` classes (eg. `Mat::fixed`, `Col::fixed`, `Row::fixed`, `Cube::fixed`).  Additionally, please keep the const return types for the `podarray` class, as that is only meant to be used internally.

**Comment by adah1972** [comment]
PR #21 is created as you suggested. Regretfully, `Mat::fixed` is not Assignable and Semiregular now (while `Mat` still is).

**Comment by conradsnicta** [comment]
Merged, with a few minor modifications. Could you test it on your end?

**Comment by adah1972** [comment]
Thanks. No problems found.

**Comment by adah1972** [comment]
FYI: Your original issue did seem to be a GCC bug, as the original code now works under GCC 7.1.

Although you probably cannot do much now for backward compatibility, at least it is possible to change the Armadillo code to make it satisfy Assignable and Semiregular fully again. So I think it is good news.

**Comment by conradsnicta** [comment]
GCC 6 is part of Debian 9, which will stick around for several years.  There is also GCC 4.8 on RHEL 7, which still also last for several more years.

**Comment by adah1972** [comment]
I know (and I just did a project with CentOS 7). At least it is possible to write `#ifdef`s to make the concepts work well, though it may not be worthwhile yet. I think I can wait till concepts become part of the C++ standard. My last comment was really FYI only.
