### ISSUE TITLE
out of bounds access in GenEigsSolver

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#26]
@yixuan - from a bug report sent via email:

_In GenEigsSolver::restart (newarp_GenEigsSolver_mean.hpp: 122) there exists the following:_
```
if(cx_attrib::is_complex(ritz_val(i), eps) && cx_attrib::is_conj(ritz_val(i), ritz_val(i + 1), eps))
```

_Unfortunately `ritz_val` has len [0, nvc), and `i` can be equal to `ncv-1`. Also see `compute`, `restart`'s invoker, and `nev_adjusted`, whose return value is used for `k` (`i`'s initialiser)._

My note: based on a quick look at the code, length of `ritz_val` indeed appears too short for `ritz_val(i + 1)`

**Comment by yixuan** [comment]
Thank Olivier and you for discovering the problem.

The code is actually logically "correct" based on the following fact: the eigenvalues of a real matrix are either real, or in conjugate complex pairs. This means that if `ritz_val[ncv - 1]` is real, then the `&&` operator is short-circuit; if `ritz_val[ncv - 1]` is complex, then `ritz_val[ncv - 2]` must also be complex, so the loop actually skips `ritz_val[ncv - 1]`.

I guess for this example there exists some rounding error in the `is_complex()` function, which incorrectly detects the type of the number. I'll look into this and modify the algorithm to avoid this danger.

**Comment by conradsnicta** [comment]
@yixuan - Thanks for looking into this :)
