### ISSUE TITLE
boolean matrix support

### ISSUE THREAD

**Issue by binxiangni** [conradsnicta/armadillo-code#29]
After looking through the documentation of Armadillo, I find that it seem not to support boolean matrix. And the multiplication of boolean matrices is quite different from that of numeric matrices. Do you have any idea how to achieve the multiplication of boolean matrices under the current framework? Will the package support that feature later?

**Comment by eddelbuettel** [comment]
@binxiangni I think that is out of scope.  From the matrix documentation:

> The root matrix class is Mat<type>, where type is one of:
float, double, std::complex<float>, std::complex<double>, short, int, long, and unsigned versions of short, int, long

As I mention `unsigned int` is used for indexing.  That is not the same as `bool`, so as @thirdwing said [over in RcppArmadillo](https://github.com/RcppCore/RcppArmadillo/pull/145#issuecomment-314325617) we should just warn (or even `stop()` / `throw` ) that this is not available.
