### ISSUE TITLE
print warnings and errors via cerr

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#31]
Investigate use of cerr for printing of warnings and errors. This would in effect result in a minor API change.

**Comment by eddelbuettel** [comment]
It would be lovely if we could carry over a similar redirect for R's use as we do for `cout`.  R Policy (for code called from R) is to have it buffer stdout and stderr.

**Comment by conradsnicta** [comment]
@eddelbuettel - as of Armadillo version 8.x, the "ARMA_DEFAULT_OSTREAM" define is no longer applicable.  Instead, use the following defines: ARMA_COUT_STREAM and ARMA_CERR_STREAM.
