### ISSUE TITLE
refactor SpMat to use dual representation

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#33]
- refactor SpMat to use dual internal representation, to allow relatively fast random element access

**Comment by conradsnicta** [comment]
@eddelbuettel - Heads up: the dual internal representation within SpMat seems to be working. However, there is a minor API change that affects converting arma::SpMat to R sparse matrices.

The SpMat<> class has a new sync() function.  The sync() function needs to be invoked to ensure that the CSC representation is valid.  In other words, sync() needs to be called before copying the associated sparse representation arrays (values, row_indices and col_ptrs) back to R.

**Comment by eddelbuettel** [comment]
Thanks @conradsnicta -- I am sure that between @binxiangni @thirdwing @coatless we'll manage.

Did you yet write-up somewhere how `spmat` and `comat` coxists or convert?  Should we (time permitting) look into `comat` adaptors?   GSoC is over, but hopefully we keep some momentum going...

**Comment by binxiangni** [comment]
@eddelbuettel Sure, I'll continue contributing to sparse matrix support in RcppArmadillo. Based on the past work, it should not be hard to convert sparse matrices in package "Matrix" to COO.

**Comment by conradsnicta** [comment]
@eddelbuettel @binxiangni - The only supported sparse matrix class is SpMat.  Any other class is assumed to be internal unless explicitly released as part of a stable release. To be clear: the only thing that's newsworthy is the new sync() function within SpMat.  If there is any other news I'll shout about it.

**Comment by eddelbuettel** [comment]
Perfect, thanks.  I just saw the CoMat changes and was wondering if it was, or wasn't, public facing.

You maintain the API very well.
