### ISSUE TITLE
Reverse subvector views

### ISSUE THREAD

**Issue by knstmrd** [conradsnicta/armadillo-code#38]
Add reverse subvector views (as a separate method, perhaps?). Currently, `.subvec(index_start, index_end)` does not work if `index_end` < `index_start`, however, such functionality might be useful.

**Comment by conradsnicta** [comment]
Sorry, we generally don't implement features on request; see http://arma.sourceforge.net/faq.html#development

If you want to have specific new functionality in Armadillo, please submit a pull request.
