### ISSUE TITLE
What arma  done? 

### ISSUE THREAD

**Issue by ShannonZ** [conradsnicta/armadillo-code#39]
What arma  done?  I find that after comment the armadillo.lib&armadillo.dll, the example still runs well.
`#include <iostream>
#include <armadillo>

#pragma comment(lib,"libopenblas.dll.a")
#pragma comment(lib,"lapack.lib")
//#pragma comment(lib,"armadillo.lib")

using namespace std;
using namespace arma;

int main()
{
	mat A = randu<mat>(4, 5);
	mat B = randu<mat>(4, 5);

	cout << A*B.t() << endl;

	system("pause");
	return 0;
}`

So what's this library done for us?
And the official documentation even not mention  armadillo.lib&armadillo.dll, Is it necessary to use cmake to generate a solution and then build it to produce the lib&dll???

**Comment by rcurtin** [comment]
I think that the question you are asking is what `armadillo.lib` and `armadillo.dll` are for.  These libraries are convenience wrappers for the underlying BLAS/LAPACK functionality and whether they are used depends on your `ARMA_USE_WRAPPER` configuration setting.  Since you're already manually linking against OpenBLAS and LAPACK in your example, then linking against `armadillo.lib` is not necessary.

**Comment by conradsnicta** [comment]
@ShannonZ - @rcurtin is right; see the Armadillo FAQ for more info:
http://arma.sourceforge.net/faq.html

**Comment by ShannonZ** [comment]
@rcurtin  Can you give me an example which only links armadillo.lib&dll?
I followed the ReadMe to build the shared lib, but the solution still throw lapack not found exception.

**Comment by rcurtin** [comment]
I don't use Windows so I am afraid I can't give a good example here.  Make sure that `ARMA_USE_WRAPPER` is enabled in your Armadillo configuration if you want to link only to `armadillo.lib` and I think it should work---assuming that linking on Windows works like I think it does...

**Comment by conradsnicta** [comment]
@ShannonZ - The cmake based installer is not really tested or supported under Windows.  As such, the use of the wrapper library is also not supported under Windows.  I suggest you use Armadillo without installation as described in the README.txt file.  (Hint: make sure that ARMA_USE_LAPACK and ARMA_USE_BLAS are enabled in `include/armadillo_bits/config.hpp` and then link directly with OpenBLAS or the provided reference versions of BLAS and LAPACK).
