### ISSUE TITLE
Please add RcppArmadillo

### ISSUE THREAD

**Issue by eddelbuettel** [conradsnicta/armadillo-code#4]
Isn't it a little rude that it is omitted here?

Related Software
- MLPACK: C++ machine learning library built on top of Armadillo
- libpca: library for principal component analysis and related transformations
- armanpy: interfaces Armadillo matrices with Python
- matlab2cpp: conversion of Matlab code to Armadillo based C++ code

My current count has 318 packages on CRAN using RcppArmadillo.  I think that is something worth mentioning.

I will test 7.700.0 later.

**Comment by conradsnicta** [comment]
The README.txt file deliberately doesn't have an exhaustive list. RcppArmadillo is mentioned twice on Armadillo's FAQ page: http://arma.sourceforge.net/faq.html

**Comment by eddelbuettel** [comment]
I was referring to this top-right paragraph [here](http://arma.sourceforge.net/download.html) and still find it puzzling that under a list of _related software_ you don't seem to care about a widely used package.
