### ISSUE TITLE
Incorrect variable name(s)?

### ISSUE THREAD

**Issue by StanislawAntol** [conradsnicta/armadillo-code#43]
Some of the recent changes make my `armadillo`-dependent code not compile anymore. It fails during the `#include <armadillo>` in my code (which mainly uses the GMM and load HDF5 portions of `armadillo`). Specifically, it fails on [this line](https://github.com/conradsnicta/armadillo-code/blob/unstable/include/armadillo_bits/auxlib_meat.hpp#L1883), because `out` is not defined within the `chol_band_common` function scope when not using `LAPACK`. (It might be good to double-check the variables names in the recently updated code for consistency, in case there are more issues.) I don't have time right now to produce a minimal script, but I think any program that tries including `armadillo` on a LAPACK-less system will cause the issue.

Thanks!

**Comment by conradsnicta** [comment]
This should now be fixed.  Commit: https://github.com/conradsnicta/armadillo-code/commit/782fb90468bdbc43854388f418f9ba6884b8095c

**Comment by StanislawAntol** [comment]
It looks like I can build fine now. Thanks!
