### ISSUE TITLE
Armadillo on smal embedded systems

### ISSUE THREAD

**Issue by jankap** [conradsnicta/armadillo-code#47]
Hello gentlemen,
I really appreciate your work put into this great library! Looks like this is exactly what I have searched for. But before trying to use it I'd like to ask a question. 
Since this is no bug report (but no feature request either), it'd be great if you could point me to the right place to ask these kinds of questions if it's not appropriate here. 

Currently I'm exactly in the situation you described in your FAQ, I'm trying to close the gap between production (embedded) code and algorithm development in Matlab. My goal is to use the same library and code in Matlab and on small embedded devices (ARM Cortex M3-M4, ~100 MHz, 20-100 kB Ram, FPU sometimes available) to reduce translation errors and the requirement of retesting the translated code (to C or C++ manually). The algorithm's requirements are not too hard (max 8x8 matrices, matrix inversion, dot products, matrix addition & multiplication). 
For performance reasons the current C firmwares use an expanded and symbolically simplified (absolutely non-generic) version of the algorithms, developed in Matlab. A more generic version would be awesome to skip the Matlab "code generation" (it's no real code generation, we do not have the "Embedded Coder" Toolbox) step. 

Did you or anybody else ever have heard of Armadillo being used in an Embedded Device context? I would not have thought of that but in section 9 of http://arma.sourceforge.net/armadillo_nicta_2010.pdf you're writing "The library can be used for converting Matlab (or Octave) based code into production quality software, useful for commercial deployments or algorithm implementation on embedded hardware." 
Do you think the library could be used on small microcontrollers (as described above) or would that require too many changes (like more constexpr or statical memory alloc and so on)?

Thank you very much and sorry if this is the wrong place to ask that question.

Best regards,
Jan

**Comment by conradsnicta** [comment]
@jankap - Hi Jan, I'm working on several other projects as well, so I currently don't have the time to look into this properly. However, I'm happy to discuss this in more details under a consulting arrangement. Please contact me via email if you're interested.

Nokia has made a modified form of an old version of Armadillo which might be useful for you: https://github.com/nokia/armadillo-with-fixed-point-support/tree/unstable
