### ISSUE TITLE
please implement index_min() and index_max() for cube

### ISSUE THREAD

**Issue by githubtomtom** [conradsnicta/armadillo-code#49]
the ideal index_min() and index_max() would support cube, and be called like:
index_min(Q, dim)
where Q is a cube and dim is in the set {0, 1, 2} (with default = 0)

Thanks.

**Comment by conradsnicta** [comment]
Sorry, we generally don't implement features on request; see http://arma.sourceforge.net/faq.html#development

If you want to have specific new functionality in Armadillo, please submit a pull request (ie. you need to implement the code).

**Comment by githubtomtom** [comment]
While a rowvec is a 1xN matrix (or 1xNx1 cube),
and a vec is a Nx1 matrix (or Nx1x1 cube),
I think the issue with the proposed cube-compatible index_min() is: Armadillo does not have a vector class for 1x1xN …..

Thank you very much anyway.

**Comment by kthohr** [comment]
@githubtomtom 
Couldn't you just iterate over .slices and .tubes to achieve this?

**Comment by conradsnicta** [comment]
@githubtomtom - maybe you can adapt the code for sum(), which handles cubes.
http://arma.sourceforge.net/docs.html#sum

**Comment by githubtomtom** [comment]
it’s done. kind of painful :<

compared to R, which is much more “causal” in “vector” (1x1xN, 1xNx1, Nx1x1 are all the same except the dim attribute), c++ is much more strict.

Of course, the speedup of C++ is also from the strict type-casting…

anyhow, after using a lot of .t(), sub2ind(), vectorise(), .tube(), .slice(), .index_min(), shed_row(), etc etc… , the problem is now solved…


By the way, in using sub2ind() I feel something strange about the “matrix_of_subscripts”:
I guess normally the matrix is more easily constructed column-wise, but somehow sub2ind() requires it to be constructed row-wise. In using sub2ind(), I have to do like:

uvec ind = sub2ind(size(Q), matsub.t() );

everytime, as matsub is naturally constructed column-wise….

Thanks.

**Comment by githubtomtom** [comment]
That’s mean, the “matrix_of_subscripts” for cube should have 3 columns rather than 3 rows ….


other “suggestions” for cube:
.each_tube()  ===> operates on the vector of the last dimension of cube
add supports of .row(), .col(), .each_row(), .each_col() for cube ===> each of the function would handle a mat.

Thanks,
Thomas
