### ISSUE TITLE
typedef for difference_type in iterators

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#50]
@rcurtin - Hi Ryan, for iterators, should the typedef for `difference_type` be `sword` (a signed int) rather than `uword` (an unsigned int) ?

According to [cplusplus.com](http://www.cplusplus.com/reference/iterator/iterator_traits/), iterators for raw pointers types seem to have `difference_type` set to [`ptrdiff_t`](http://www.cplusplus.com/reference/cstddef/ptrdiff_t/), which is an alias for a signed integer type.

At cppreference.com, the corresponding docs for [iterator_traits](http://en.cppreference.com/w/cpp/iterator/iterator_traits) also [indicate](http://en.cppreference.com/w/cpp/iterator/iterator_traits) that "ptrdiff_t is the signed integer type of the result of subtracting two pointers".

`difference_type` in Mat, as part of the `row_col` iterator:
https://github.com/conradsnicta/armadillo-code/blob/unstable/include/armadillo_bits/Mat_bones.hpp#L587

`difference_type` in SpMat:
https://github.com/conradsnicta/armadillo-code/blob/unstable/include/armadillo_bits/SpMat_bones.hpp#L360

There are at least 2 further problems:
(1) Does subtracting two iterators even work?  There doesn't seem to be an associated `operator-()` for the sparse iterators, nor the `row_col` iterator in Mat.
(2) Does subtracting sparse iterators make sense?  The difference between two iterators is not guaranteed to point to an existing non-zero element.

Assuming that for sparse matrices iterator subtraction is a bad idea, it would be tempting to remove the `difference_type` typedef.  However, it seems that in C++17 the [rule](http://en.cppreference.com/w/cpp/iterator/iterator_traits) is: "if Iterator does not have the five member types difference_type, value_type, pointer, reference, and iterator_category, then this template has no members by any of those names".  Not sure what the C++ committee was smoking at the time.

**Comment by rcurtin** [comment]
I think the standard makes sense to me---a valid C++ iterator has to have all five of those traits.  These were added after a discussion many years ago, in which, if I am remembering right, a user said that he needed to be able to treat matrix iterators as an STL iterator for some functionality he was using.

I think that you are right that `difference_type` should be `sword`; I guess this justifies the comment `not certain on this one`. :)

For the further problems:

(1) Right now there is no `operator-()` for either, but it could be implemented.  For `row_col_iterator` this is straightforward.  Let me know if you'd like me to implement that.

(2) This one is a little tricky and depends on what a sparse iterator "means".  In my view a sparse iterator should loop over the nonzero values in the matrix, and its internal "position" is the nonzero element it currently points to.  If that is the case, then subtraction of two iterators (which must point to the same matrix) will simply be the difference in number of nonzero values between their locations.  I think that this is reasonable enough from a data structures perspective.

Let me know what you think.  Depending on what your opinion is, I can supply a patch to fix these issues and implement `operator-()`.

**Comment by conradsnicta** [comment]
After looking more thorougly at the requirements for [random_access_iterator](http://www.cplusplus.com/reference/iterator/RandomAccessIterator/) and [bidirectional_iterator](http://www.cplusplus.com/reference/iterator/BidirectionalIterator/), it seems that worrying about the exact definition of `difference_type` is moot.  Apologies - I should have spotted this earlier.

An iterator which has the `random_access_iterator_tag` needs to support "_arithmetic operators + and - between an iterator and an integer value, or subtracting an iterator from another_".  In contrast, an iterator which has the `bidirectional_iterator_tag` appears to not have such requirements.  (cppreference essentially says the same thing: [RandomAccessIterator](http://en.cppreference.com/w/cpp/concept/RandomAccessIterator) vs [BidirectionalIterator](http://en.cppreference.com/w/cpp/concept/BidirectionalIterator) concepts).

All the custom iterators in Armadillo have their category as `bidirectional_iterator_tag`, so any conforming user code would not use `difference_type` anyway.  It's probably best to keep the iterators as "simple" bidirectional iterators -- I'm not keen on extending them to be random access, as that opens a whole new can of worms.

However, it would be good to be explicit in the source code and indicate that the `difference_type` should not be used, as well as prevent malformed user code from using it.  Should we explicitly use a `difference_type` which is a junk type (eg. an empty struct) ?    Something along these lines:
    
    struct not_used_difference_type {};
    
and within iterator definitions:

    typedef not_used_difference_type difference_type;

**Comment by rcurtin** [comment]
I agree with that---random access iterators are *possible* for matrices, but, it's tough for me to see the immediate need to implement them.  So let's avoid that for now.

The junk type idea is fine by me.  I'm not sure if any STL algorithms built for bidirectional iterators depend on `difference_type`, but you are right that this provides an easier path to debugging malformed user code.
