### ISSUE TITLE
arma sourceforge is down

### ISSUE THREAD

**Issue by pati-ni** [conradsnicta/armadillo-code#52]
Any idea when the site is going to go up again? Alternative mirrors?

**Comment by conradsnicta** [comment]
@pati-ni @rcurtin 
SourceForge is migrating websites + etc to a new datacenter.  Updates on the progress are posted at:
https://twitter.com/sfnet_ops

Partial functionality is back online. To download Armadillo manually, see this site:  https://sourceforge.net/projects/arma/

If you need access to the API documentation, see the `docs.html` file within the Armadillo .tar.xz archive.

**Comment by rcurtin** [comment]
It's very surprising to me that a website as important as Sourceforge didn't do this in such a way that minimized downtime for all projects.

**Comment by eddelbuettel** [comment]
@conrad:  Time to register a domain like 
 armadillo-lib.org
 armadillo-project.net
etc pp and redirect to pages hosted (for free) at GH or another static page host?

**Comment by eddelbuettel** [comment]
Needless to say you _already have_ armadillo-code.github.io by virtue of having this repo.  You only need to turn the website on in settings (and these days you can have the `docs/` serve instead of having to use a `gh-pages` branch).

**Comment by conradsnicta** [comment]
Update: the arma website is back online. The SF folks could have certainly handled this in a smoother manner.

@eddelbuettel - registration and/or use of alternative hosting provider is certainly a possibility. at the same time, places like GH also have downtime. with GH i'd be putting all the eggs in one basket, which i'm not comfortable with. with a separate hosted website there are ongoing costs.

**Comment by eddelbuettel** [comment]
There are other free static hosting sites (ie [netlify](https://www.netlify.com/)) .  And if you were to compare downtimes, SF is clearly worst which is my point. Plus the other often use CDN and deliver faster.  But your call. as always.

**Comment by coatless** [comment]
@conradsnicta more than happy to help setup the netlify integration w/ the git repo. Sourceforge is a toxic place for oss. Also, have you considered moving armadillo to its own github org?

**Comment by conradsnicta** [comment]
@coatless - There will be a mirror of armadillo sf pages on a separate site when I release armadillo 8.500. Not on netlify, as that's too young of an organisation. It also won't be on GitHub, as that's putting too many eggs in one basket.
