### ISSUE TITLE
binary search for accessing SpMat elements

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#53]
@rcurtin - I've modified `SpMat::get_value()` to use binary search instead of linear search.  This results in considerable speedups for element access.  Could you have a look at the code to see if anything is missing?
https://github.com/conradsnicta/armadillo-code/blob/50a8a3d1c52761504465824b9483b2a42dafdb56/include/armadillo_bits/SpMat_meat.hpp#L5449

https://github.com/conradsnicta/armadillo-code/blob/50a8a3d1c52761504465824b9483b2a42dafdb56/include/armadillo_bits/SpMat_meat.hpp#L5384

**Comment by rcurtin** [comment]
Assuming this passes the regression tests, it looks great to me.  `std::lower_bound()` is a much better solution.

I do believe there may be some legacy code (especially in the iterators) that still doesn't use a binary search over the elements and instead uses a linear search, but what we choose to do with that depends on the end state of the iterators.  Some months ago I worked on replacing `SpMat::iterator` with `MapMat::iterator`, but I did not use `std::lower_bound()` or compare with it there.  My current opinion is that despite the ugliness, the `SpMat` iterators are faster, but they could be adapted to use `std::lower_bound()` and `std::upper_bound()` for some additional speedup in places.  I can look into that if you like.

**Comment by conradsnicta** [comment]
Regression tests show no problems, though it's always good to be paranoid whenever indirection and  pointer arithmetic are involved.

It looks like SpMat::row_iterator uses a convoluted form of linear search.  One possible option would be to rewrite SpMat::row_iterator by modelling it after the simple Mat::row_iterator, with calls to .at()  replaced by .get_value() and any non-zero values produced by .get_value() simply skipped.  It's a bit suboptimal, but it might very well be faster what we have now, given that .get_value() now has binary search.

Another option would be to adapt the code from .get_value() directly into SpMat::row_iterator.
