### ISSUE TITLE
Prevent Linking to OpenBLAS 

### ISSUE THREAD

**Issue by nickjhathaway** [conradsnicta/armadillo-code#58]
Hi, 
When I link to OpenBLAS libraries it for some odd reason breaks some other libraries I'm linking to, is there a way to tell the cmake installer to not look for OpenBLAS when installing armadillo so it won't link to it? I tried looking through the CmakeLists but I couldn't figure out a way to do so but I'm not very familiar with cmake so sorry if there's an obvious way of doing it I'm not seeing. 

Thanks!

Nick

**Comment by conradsnicta** [comment]
In CMakeLists.txt, right after the line with `include(ARMA_FindOpenBLAS)`, try adding something along these lines:
`set(OpenBLAS_FOUND false)`

Or preferably, remove OpenBLAS from your system, as it seems to be installed incorrectly.

**Comment by nickjhathaway** [comment]
Thanks, that worked. I would remove but I don't manage the cluster I'm working on and don't have the admin right to do so.

**Comment by conradsnicta** [comment]
It's also possible to install OpenBLAS locally (ie. in your home dir) and then manually link with it.  See this question on the [Armadillo FAQ page](http://arma.sourceforge.net/faq.html#linking): "How can I use Armadillo with OpenBLAS installed in a non-standard location?"
