### ISSUE TITLE
Cannot create matrix for max-plus algebra

### ISSUE THREAD

**Issue by Lecrapouille** [conradsnicta/armadillo-code#61]
Hi ! For implementing some computations in Max-Plus algebra (https://en.wikipedia.org/wiki/Max-plus_algebra) I implemented the following class but I cannot use it with Armadillo (in accord with the FAQ).
```
template<class T>
class MaxPlus
{
public:

  MaxPlus() : val() {};
  MaxPlus(const MaxPlus & d) : val(d.val){}
  MaxPlus(const T t) : val(t){}
  inline bool operator==(const MaxPlus &rhs) const { return val == rhs.val; }
  inline bool operator==(const T &rhs) const { return val == rhs; }
  inline MaxPlus & operator=(const MaxPlus & rhs) { val = rhs.val; return *this;}
  inline MaxPlus & operator=(const T rhs) { val = rhs; return *this;}
  inline T operator*=(const MaxPlus & rhs) { val += rhs.val; return val; }
  inline T operator+=(const MaxPlus & rhs) { val = std::max(val, rhs.val); return val; }
  inline T operator*(const MaxPlus & rhs) const { return val + rhs.val; }
  inline T operator+(const MaxPlus & rhs) const { return std::max(val, rhs.val); }
  inline T operator/(const MaxPlus & rhs) const { return val - rhs.val; }
  inline T operator-(const MaxPlus & rhs) const { return val - rhs.val; }
  inline T operator-() const { return -val; }
  inline T operator+() const { return val; }

  //inline operator const T & () const { return val; }
  //inline operator T & () { return val; }

  T val;
};

using fMaxPlus = MaxPlus<float>;
arma::Mat<fMaxPlus> A;
```
This class is working with my naive C++ Matrix class but have you some suggestions on how to overload matrix element operator+() and operator*() with Armadillo ? Thanks !

**Comment by conradsnicta** [comment]
>    using fMaxPlus = MaxPlus<float>;
>    arma::Mat<fMaxPlus> A;

It's currently beyond the scope of Armadillo to support element types other than int, long, float, double, std::complex<float>, std::complex<double>. Many low-level changes would be required.

**Comment by conradsnicta** [comment]
>    using fMaxPlus = MaxPlus<float>;
>    arma::Mat<fMaxPlus> A;

It's currently beyond the scope of Armadillo to support element types other than int, long, float, double, std::complex[float], std::complex[double]. Many low-level changes would be required.
