### ISSUE TITLE
Armadillo 8.500-RC1 (Release Candidate 1)

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#62]
Armadillo 8.500-RC1 (Release Candidate 1) contains new features, enhancements, speedups and bug fixes.
Download: http://sourceforge.net/projects/arma/files/armadillo-8.500-RC1.tar.xz
Please test and report any regressions or bugs.

Changes:
- faster [element access](http://arma.sourceforge.net/docs.html#element_access) in sparse matrices
- faster [row iterators](http://arma.sourceforge.net/docs.html#iterators_spmat) for sparse matrices
- faster handling of compound expressions by [trace()](http://arma.sourceforge.net/docs.html#trace)
- expanded [normalise()](http://arma.sourceforge.net/docs.html#normalise) to handle sparse matrices
- expanded [.transform()](http://arma.sourceforge.net/docs.html#transform) and [.for_each()](http://arma.sourceforge.net/docs.html#for_each) to handle sparse matrices
- added [reverse()](http://arma.sourceforge.net/docs.html#reverse) for reversing order of elements
- added [roots()](http://arma.sourceforge.net/docs.html#roots) for finding the roots of a polynomial

CC: @StanislawAntol @neumannrf @knedlsepp @coatless @eddelbuettel @h00shi @nickjhathaway @titaschanda @zoq @JWichmann @sbrodehl @dexterurbane

**Comment by neumannrf** [comment]
Great news @conradsnicta !
Will `reverse()` replace `flipud()` and `fliplr()`?

**Comment by knedlsepp** [comment]
Builds fine on my machines. Do you consider adding a target "make test" for the unit tests?

**Comment by conradsnicta** [comment]
@neumannrf - fliplr() and flipud() will stay for compatibility reasons; you can think of reverse() as a generalised version of fliplr() and flipud(), with better / easier handling of vectors (ie. works with row and column vectors, without worrying about orientation).

**Comment by eddelbuettel** [comment]
No (new) issues on CRAN either. Log from testing at 450+ reverse dependencies is [here](https://github.com/RcppCore/rcpp-logs/commit/fd769976ca89127a2ebdac310e5f682192fb3815).

**Comment by conradsnicta** [comment]
@eddelbuettel - Great! Thanks for running the tests

**Comment by conradsnicta** [comment]
update: Armadillo 8.500 released; http://arma.sourceforge.net/download.html

**Comment by eddelbuettel** [comment]
Yes, it's been at CRAN since the 21st. I'll ping them tomorrow; there was also an R release since.
