### ISSUE TITLE
(Sparse x dense) very much slower than (dense x sparse) or (sparse x sparse)

### ISSUE THREAD

**Issue by Hong-Revo** [conradsnicta/armadillo-code#70]
First, I want to say it's great to be able to use a scientific software library developed here in Oz.

I've come across a weird problem when working with sparse matrices though. When I multiply (sparse x dense), it's about 2 orders of magnitude slower than the reverse, or with (sparse x sparse). This is with Armadillo 8.400.

Here's some matrix multiply functions that use RcppArmadillo to interface Arma with R:

```cpp
// [[Rcpp::depends(RcppArmadillo)]]
#include <RcppArmadillo.h>

// [[Rcpp::export]]
arma::sp_mat mult_sp_den_to_sp(arma::sp_mat& a, arma::mat& b)
{
    // sparse x dense -> sparse
    arma::sp_mat result(a * b);
    return result;
}

// [[Rcpp::export]]
arma::sp_mat mult_den_sp_to_sp(arma::mat& a, arma::sp_mat& b)
{
    // dense x sparse -> sparse
    arma::sp_mat result(a * b);
    return result;
}
```
When I run this, I get the following timings on my potato laptop (all in seconds):
```r
set.seed(98765)
# 10000 x 10000 sparse matrices, 99% sparse
a <- rsparsematrix(1e4, 1e4, 0.01, rand.x=function(n) rpois(n, 1) + 1)
b <- rsparsematrix(1e4, 1e4, 0.01, rand.x=function(n) rpois(n, 1) + 1)

# dense copies
a_den <- as.matrix(a)
b_den <- as.matrix(b)

system.time(mult_sp_den_to_sp(a, b_den))
#   user  system elapsed 
# 508.66    0.79  509.95 

system.time(mult_den_sp_to_sp(a_den, b))
#   user  system elapsed 
#  13.52    0.74   14.29 
```
Oddly, if I simply make a sparse copy of the dense mat, then the speed problem is solved:
```cpp
// [[Rcpp::export]]
arma::sp_mat mult_sp_den_to_sp2(arma::sp_mat& a, arma::mat& b)
{
    // sparse x dense -> sparse
    // copy dense to sparse, then multiply
    arma::sp_mat temp(b);
    arma::sp_mat result(a * temp);
    return result;
}
```
```r
system.time(mult_sp_den_to_sp2(a, b_den))
#   user  system elapsed 
#   5.45    0.41    5.86 
```
Should Arma perhaps be doing this by default?

I also [asked this on StackOverflow](https://stackoverflow.com/questions/49771093/sparse-x-dense-matrix-multiply-unexpectedly-slow-with-armadillo), but didn't get any answers that really addressed the issue.

**Comment by conradsnicta** [comment]
sparse x dense is currently not very efficient with CSC storage.  However, the unstable branch of Armadillo on github has openmp-based speedups for sparse x dense.  This will become Armadillo 8.500.  Can you try that and let us know whether it works for you?

You will need to enable openmp in your compiler.  For example, use `-fopenmp` in gcc or clang.

**Comment by conradsnicta** [comment]
@Hong-Revo - I've reworked the code for sparse * dense multiplication. It should be much faster now for your use case.

@rcurtin - Ryan, could you have a look at the corresponding code, to make sure everything is ok?  The code now uses explicit transposes prior to multiplication, since the transpose function is now much faster.
https://github.com/conradsnicta/armadillo-code/blob/ee2195a8a68cd8a67487d76b311006fba67afec1/include/armadillo_bits/spglue_times_meat.hpp#L317

**Comment by dselivanov** [comment]
I also was thinking about double transpose. But is transposing of sparse matrix a cheap operation? (intuitively looks it is not - involves sorting)

**Comment by conradsnicta** [comment]
@dselivanov - I recently reworked the transpose operation to be much faster. No sorting required. See the new code:
https://github.com/conradsnicta/armadillo-code/blob/100571081ff90780db808c65b07bd1ec5c2ea6ff/include/armadillo_bits/spop_strans_meat.hpp#L25

**Comment by Hong-Revo** [comment]
I talk to Arma via RcppArmadillo, so it's hard for me to test new builds. Still, I can't see why this shouldn't be a big improvement.

I'm wondering though, why not just convert the dense matrix to sparse, and do a sparse-sparse multiply? This was very efficient when I tried it.

**Comment by conradsnicta** [comment]
@Hong-Revo - Dense can always be converted to sparse (and vice versa), but then why keep data in a dense matrix when it is actually sparse?  The problem with always having an automatic conversion is that we do not know a-priori whether conversion to sparse will help or make things worse.

You can always forcefully convert a dense matrix to sparse format before an operation. For example:
    
       mat A;
    sp_mat B;
    sp_mat C = sp_mat(A) * B;  // forcefully convert A to sparse format before multiplication

**Comment by Hong-Revo** [comment]
@conradsnicta No worries, I was just curious.

I've given RC2 a test run, and it appears to have solved the problem. Thanks again for the great work!
