### ISSUE TITLE
Armadillo 8.500-RC2 (Release Candidate 2)

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#71]
Armadillo 8.500-RC2 (Release Candidate 2) contains new features, enhancements, speedups and bug fixes.
Download: http://sourceforge.net/projects/arma/files/armadillo-8.500-RC2.tar.xz
Please test and report any regressions or bugs.

Changes since 8.500-RC1:
- faster [transpose](http://arma.sourceforge.net/docs.html#trans) of sparse matrices
- faster sparse * dense matrix multiplication
- faster handling of sparse matrices by [trace()](http://arma.sourceforge.net/docs.html#trace)
- added [repelem()](http://arma.sourceforge.net/docs.html#repelem) for replicating elements

CC: @eddelbuettel @coatless @dselivanov @sh-zheng @kthohr @Hong-Revo @neumannrf @knedlsepp

**Comment by eddelbuettel** [comment]
No issues from my end.

**Comment by coatless** [comment]
Ditto. This is great! 

@conradsnicta Any chance you could publish a set of contributing guidelines? I'm itching to implement a sparse kronecker product.

**Comment by conradsnicta** [comment]
@coatless - Sparse kron() is already implemented: see the code [here](https://github.com/conradsnicta/armadillo-code/blob/62be0d40903554c9cfac4579457d9aec5825b1f2/include/armadillo_bits/fn_kron.hpp#L93) and [here](https://github.com/conradsnicta/armadillo-code/blob/62be0d40903554c9cfac4579457d9aec5825b1f2/include/armadillo_bits/spglue_kron_meat.hpp).  However, it can always be made faster, eg. by directly writing in CSC format.
