### ISSUE TITLE
c++11

### ISSUE THREAD

**Issue by drjdn** [conradsnicta/armadillo-code#75]
The following code:

```cpp
#include <armadillo>
#include <iostream>

using namespace std;
using namespace arma;

int main() {

  mat A = mat(2,4);
  cout << A << endl;
  A.ones();
  cout << A << endl;
  A.randu();
  cout << A << endl;  

  return 0;
}
```
compiled as follows:

```bash
g++ test.cpp -Larmadillo
```
produces the following error:

```bash
/tmp/cc0KiUcm.o: In function `TLS wrapper function for arma::arma_rng_cxx11_instance':
test.cpp:(.text._ZTWN4arma23arma_rng_cxx11_instanceE[_ZTWN4arma23arma_rng_cxx11_instanceE]+0x21): undefined reference to `arma::arma_rng_cxx11_instance'
collect2: error: ld returned 1 exit status
```
If compiled as:

```bash
g++ -std=c++98 test.cpp -Larmadillo
```
it gives the following warning/NOTE:

```bash
In file included from /usr/include/armadillo:54:0,
                 from test.cpp:1:
/usr/include/armadillo_bits/compiler_setup.hpp:510:108: note: #pragma message: NOTE: suggest to enable C++14 mode for faster code; add -std=c++14 to compiler flags
     #pragma message ("NOTE: suggest to enable C++14 mode for faster code; add -std=c++14 to compiler flags")
```
but runs as expected.  I'm on a x86-64 machine running Manjaro Linux with gcc version 7.3.1 and armadillo 8.5.0.  If you comment out the call to the RNG it works fine.  I also have an up to date instance of Ubuntu 16.04 in virtualbox (gcc 5.4 and armadillo 6.5.0) that also works correctly without any warning/NOTE.  However, under Ubuntu if you compile with:

```bash
g++ -std=c++11 test.cpp -Larmadillo
```
it will fail with an error about `arma::arma_rng_cxx11_instance'. 

Best regards,
Jason

**Comment by conradsnicta** [comment]
@drjdn - change `-Larmadillo` to `-larmadillo`

The difference between capital `L` and lowercase `l` matters.
`-L` specifies a folder that gcc should search when linking, while `-l` specifies the library to link with.

Almost all command line programs (like gcc) have case sensitive options.

**Comment by drjdn** [comment]
Damn, sorry about that!  I know the difference... I've been trying to get armadillo to work in ROOT/cling and the typo above was confirmation bias.  Clearly I'm not loading the shared library correctly.  If I comment out the call to the RNG it runs fine.. so the RNG is in the shared library... duh.

**Comment by conradsnicta** [comment]
@drjdn - yes, see the [FAQ](http://arma.sourceforge.net/faq.html#linking)

**Comment by drjdn** [comment]
Just in case anyone finds this and is interested in running armadillo in ROOT/cling see:

https://root-forum.cern.ch/t/using-armadillo-in-cling/28940

Cheers,
Jason
