### ISSUE TITLE
potential move away from GitHub

### ISSUE THREAD

**Issue by conradsnicta** [conradsnicta/armadillo-code#78]
@rcurtin @eddelbuettel @kthohr 
If the following report turns out to be true, https://www.bloomberg.com/news/articles/2018-06-03/microsoft-is-said-to-have-agreed-to-acquire-coding-site-github , ie. Microshaft acquiring GitHub, then I will move the Armadillo source code repo to an alternative hosting site.

I will not be feeding the 800 pound gorilla, which is a known and continual belligerent towards open source software.

**Comment by rcurtin** [comment]
I've heard good things about Gitlab as an alternative.

**Comment by kthohr** [comment]
Indeed, not a great day for Open Source. One can only hope that their approach to developing Visual Studio Code will influence any plans for this platform.

Re Gitlab:
![image](https://user-images.githubusercontent.com/7785502/40894719-8389271a-6779-11e8-8419-35d100e8aa16.png)

**Comment by eddelbuettel** [comment]
Two things:
- I am among the most card-carrying MSFT haters in the past you can find. I still hate Windows with a passion.  I also warned often and frequently about betting everything on Github -- a VC funded commercial entity. Yet this story leaves me going "so what" -- the current MSFT seems different from the Gates/Ballmer "open source is evil" firm. I'd wait and see.
- I use Gitlab quite a bit. For personal projects (as we can have "private for free").  Now also with the [Debian-hosted-on-its-Gitlab instance](https://salsa.debian.org/edd/). It is way clumsier that Github.

So I would argue for wait and see. Git is git. You can carry anywhere. I also host ("headless" / "GUI"-less) git on my own machine.  I'd say no panic yet.

**Comment by conradsnicta** [comment]
Microshaft is still an evil entity. One example is the continual racket with Android "patents", where MS threatens device manufacturers with immediate litigation unless they sign an NDA in order to even see what patents have been allegedly "infringed".

Yet another example are the recent snafus with forced Windoze 8 -> Windoze 10 upgrades, breaking people's computers in the process.  The same process was repeated just in the last month, where a large Windoze 10 update was forced down users throats, even those that have explicitly opted out.

One of the characteristics MS has evolved in order to survive is the infamous "Embrace, Extend and Extinguish" approach. I see no evidence that they have abandoned this approach. We are at the Embrace stage. I'm not sticking around to indirectly help them with latter stages.

**Comment by eddelbuettel** [comment]
Ah, yes, Conrad will always be Conrad.  I know, as I have these tendencies myself.  When I typed the three paragraphs I knew they would not matter.

But if your mind is already set (based on products that no matter for them), fine. Do what you gotta do.
 
Just don't waste our time asking for input if you have no plan of actually making use of.

**Comment by dselivanov** [comment]
+1 to Dirk. Now days Microsoft is not worse than Google, Facebook, Apple, Amazon, etc. All are making money and all do patent racket.
Also +1 about that working with Gitlab feels much  more clunky.

**Comment by conradsnicta** [comment]
@dselivanov - You mean they're all evil in slightly different ways :)  Notwithstanding, MS certainly does not have a good track record here, and it is still actively working against open source on several fronts (OOXML anyone?).  A leopard does not lose its well-ingrained spots (ie. internal culture) just because a new CEO is on the scene. The abhorrent shit that MS pulled for many years is simply not forgivable, and the same culture, conditions and attitude still exist. If this company were a person, they'd be convicted and rotting in jail for the next 100 years.

Compare that to Google, which is definitely not a saint on several dimensions, but it actively contributes to and promotes open source software.

**Comment by eddelbuettel** [comment]
Conrad: You are relieving battles from 10 years ago.  The firm with the most committer on GitHub, to open source projects, is Microsoft.  They know they need to own "cloud" which requires "open".  We are all fighting / re-arguing the last battle here.  It's the wrong discussions.

Looking forward to beers in Brisbane you.  If I can get you away from family for an evening or two, there could be fireworks :)

**Comment by conradsnicta** [comment]
@eddelbuettel - This is not about battles now or years ago. It's a matter of principle. MS is simply not a trustworthy entity.

**Comment by eddelbuettel** [comment]
I am happy to hear how the always-for-profit GitHub was trustworthy before today.  Take your time.

As I said above, I should have known better.  This was never going to be a sensible thread.
